// <auto-generated />
using ConsoleVinivius.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleVinivius.Migrations
{
    [DbContext(typeof(ViniciusContext))]
    [Migration("20181129191037_addtabcasa")]
    partial class addtabcasa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleVinivius.Model.TabCasa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("Numero")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.ToTable("tabCasa");
                });

            modelBuilder.Entity("ConsoleVinivius.Model.Tablog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("tablog");
                });

            modelBuilder.Entity("ConsoleVinivius.Model.Tablogin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Senha")
                        .HasColumnName("senha")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Situacao")
                        .HasColumnName("situacao")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Usuario")
                        .HasColumnName("usuario")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("tablogin");
                });
#pragma warning restore 612, 618
        }
    }
}
